package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/joechenrh/golem/internal/config"
)

// runInit is the interactive setup wizard for first-time users.
// It creates ~/.golem/ directories, writes config.env with the user's
// LLM provider and API key, and optionally scaffolds persona files.
func runInit() {
	scanner := bufio.NewScanner(os.Stdin)
	prompt := func(question, defaultVal string) string {
		if defaultVal != "" {
			fmt.Printf("%s [%s]: ", question, defaultVal)
		} else {
			fmt.Printf("%s: ", question)
		}
		if scanner.Scan() {
			val := strings.TrimSpace(scanner.Text())
			if val != "" {
				return val
			}
		}
		return defaultVal
	}

	home := config.GolemHome()

	fmt.Println("Welcome to golem! Let's set up your configuration.")
	fmt.Println()

	// 1. LLM provider.
	provider := prompt("LLM provider (openai, anthropic, or custom)", "openai")

	// 2. API key.
	envKey := strings.ToUpper(provider) + "_API_KEY"
	apiKey := prompt(fmt.Sprintf("API key (%s)", envKey), "")
	if apiKey == "" {
		fmt.Fprintf(os.Stderr, "Warning: no API key provided. Set %s in ~/.golem/config.env later.\n", envKey)
	}

	// 3. Model.
	defaultModel := provider + ":gpt-4o"
	if provider == "anthropic" {
		defaultModel = "anthropic:claude-sonnet-4-20250514"
	}
	model := prompt("Model", defaultModel)

	// 4. Custom base URL (for non-standard providers).
	var baseURL string
	if provider != "openai" && provider != "anthropic" {
		baseURL = prompt(fmt.Sprintf("Base URL (%s_BASE_URL)", strings.ToUpper(provider)), "")
	}

	// 5. Create directories.
	dirs := []string{
		home,
		filepath.Join(home, "tapes"),
		filepath.Join(home, "skills"),
		filepath.Join(home, "plugins"),
		filepath.Join(home, "agents", "default"),
	}
	for _, d := range dirs {
		if err := os.MkdirAll(d, 0o755); err != nil {
			fmt.Fprintf(os.Stderr, "Error creating %s: %v\n", d, err)
			os.Exit(1)
		}
	}

	// 6. Write global config.env.
	configPath := filepath.Join(home, "config.env")
	if _, err := os.Stat(configPath); err == nil {
		overwrite := prompt(configPath+" already exists. Overwrite?", "n")
		if !strings.HasPrefix(strings.ToLower(overwrite), "y") {
			fmt.Println("Skipping config.env (keeping existing).")
			goto persona
		}
	}
	{
		var b strings.Builder
		fmt.Fprintf(&b, "# Golem global configuration\n")
		fmt.Fprintf(&b, "# Generated by golem init\n\n")
		fmt.Fprintf(&b, "GOLEM_MODEL=%s\n", model)
		if apiKey != "" {
			fmt.Fprintf(&b, "%s=%s\n", envKey, apiKey)
		}
		if baseURL != "" {
			fmt.Fprintf(&b, "%s_BASE_URL=%s\n", strings.ToUpper(provider), baseURL)
		}
		fmt.Fprintf(&b, "\n# Uncomment to enable:\n")
		fmt.Fprintf(&b, "# GOLEM_METRICS_PORT=9090\n")
		fmt.Fprintf(&b, "# GOLEM_CLASSIFIER_MODEL=openai:gpt-4o-mini\n")

		if err := os.WriteFile(configPath, []byte(b.String()), 0o600); err != nil {
			fmt.Fprintf(os.Stderr, "Error writing %s: %v\n", configPath, err)
			os.Exit(1)
		}
		fmt.Printf("Wrote %s\n", configPath)
	}

persona:
	// 7. Optionally scaffold persona files.
	createPersona := prompt("Create persona files (SOUL.md, AGENTS.md)?", "y")
	if strings.HasPrefix(strings.ToLower(createPersona), "y") {
		agentDir := filepath.Join(home, "agents", "default")

		soulPath := filepath.Join(agentDir, "SOUL.md")
		if _, err := os.Stat(soulPath); os.IsNotExist(err) {
			soul := "You are golem, a helpful AI coding assistant.\n\n" +
				"You are precise, concise, and action-oriented. When you have enough\n" +
				"information to act, you use tools directly rather than explaining what\n" +
				"you plan to do.\n"
			os.WriteFile(soulPath, []byte(soul), 0o644)
			fmt.Printf("Wrote %s\n", soulPath)
		}

		agentsPath := filepath.Join(agentDir, "AGENTS.md")
		if _, err := os.Stat(agentsPath); os.IsNotExist(err) {
			agents := "# Behavioral Rules\n\n" +
				"- Always read files before editing them.\n" +
				"- Run tests after making code changes.\n" +
				"- Keep responses concise — prefer action over explanation.\n"
			os.WriteFile(agentsPath, []byte(agents), 0o644)
			fmt.Printf("Wrote %s\n", agentsPath)
		}

		memoryPath := filepath.Join(agentDir, "MEMORY.md")
		if _, err := os.Stat(memoryPath); os.IsNotExist(err) {
			os.WriteFile(memoryPath, []byte("# Memory\n\n"), 0o644)
			fmt.Printf("Wrote %s\n", memoryPath)
		}
	}

	// 8. Validate the config by attempting to load it.
	fmt.Println()
	if _, err := config.Load("default", nil); err != nil {
		fmt.Fprintf(os.Stderr, "Warning: config validation failed: %v\n", err)
		fmt.Println("You may need to edit ~/.golem/config.env to fix the issue.")
	} else {
		fmt.Println("Configuration valid. Run `golem` to start!")
	}
}
